### ISSUE TITLE
Prevents the escape button from being pressed

### ISSUE THREAD

**Issue by FrostBird347** [msioen/MenuBarCodeReader#12] opened 2022-02-08 06:01 UTC
Version: 10.14.6

It took forever for me to figure out what was causing this issue, but whenever I have MenuBarCodeReader open the escape button does not work.
It doesn't matter if I use my actual keyboard or applescript's key codes, no programs detect the escape button being pressed down while this application is open.
Pressing down the fn key bypasses this issue.

https://user-images.githubusercontent.com/39435218/152927351-1b63da19-347b-4114-a690-763d11b80be9.mov

**Comment by msioen** [comment] 2022-02-08 15:15
Thank you for the report, I'll check it out. I've had some sporadic issues with escaping myself but never realised my own app could be the root cause

**Comment by msioen** [comment] 2022-02-09 20:59
There's a new release available with a fix for this. Normally should auto-download through 'check for updates', alternatively also downloadable from the releases page.

**Closed as completed by msioen** 2022-02-09 20:59 UTC
